awwardapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns=[
    url('^$',views.welcome,name = 'welcome'),
    url(r'^new/upload$', views.upload_image, name='upload'),
    url(r'^new/profile$', views.add_profile, name='edit'),
    url(r'^myprofile$', views.my_profile, name='myprofile'),
    url(r'^comment/(\d+)/$', views.add_comment, name='comment'),
    url(r'^search/',views.search_users, name = 'searchs'),
    # url(r'^likes/(?P<id>\d+)',views.likes, name = 'like'),
    url(r'^rate/(\d+)$',views.rating,name='rating'),
    url(r'^api/profile/$', views.ProfileList.as_view(), name = 'profile'),
    url(r'^api/project/$', views.ProjectList.as_view(), name = 'project')
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

awwardproj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('awwardapp.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
]

awwardapp/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
import numpy as np


class Profile(models.Model):
    firstname = models.CharField(max_length =30)
    lastname = models.CharField(max_length =30)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    profile_photo = models.ImageField(upload_to = 'profile_photos/', null=True)
    bio = HTMLField()
    date = models.DateTimeField(auto_now_add=True)
    # followers = models.ManyToManyField(User, blank=True, related_name='user_followers')

    @classmethod
    def get_all_awwardproj_users(cls):
        awwardproj_users = cls.objects.all()
        return awwardproj_users

    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    @classmethod
    def update_profile(cls,id,value):
        cls.objects.filter(id = id).update(user_id = new_user)

    @classmethod
    def search_by_profile(cls,username):
        certain_user = cls.objects.filter(user__username__icontains = username)
        return certain_user

def __str__(self):
        return self.user



class Project(models.Model):
    image = models.ImageField(upload_to = 'images/')
    project_name = models.CharField(max_length =10)
    project_url = models.CharField(max_length =50)
    location = models.CharField(max_length =10)
    profile = models.ForeignKey(Profile, null = True,related_name='project')
    pub_date = models.DateTimeField(auto_now_add=True, null=True)
    user= models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-pk']

    def save_project(self):
        self.save()
    
    @classmethod
    def get_project(cls, profile):
        project = Project.objects.filter(Profile__pk = profile)
        return project
    
    @classmethod
    def get_all_projects(cls):
        project = Project.objects.all()
        return project

    @classmethod
    def search_by_profile(cls,search_term):
        projo = cls.objects.filter(profile__name__icontains=search_term)
        return projo

    @classmethod
    def get_profile_projects(cls, profile):
        project = Project.objects.filter(profile__pk = profile)
        return project

    @classmethod
    def find_project_id(cls, id):
        identity = Project.objects.get(pk=id)
        return identity

    def average_rating(self):
        all_ratings = list(map(lambda x: x.design_rating, self.rate_set.all()))
        all_ratings = list(map(lambda x: x.content_rating, self.rate_set.all()))
        all_ratings = list(map(lambda x: x.usability_rating, self.rate_set.all()))
        return np.mean(all_ratings)



class Comments(models.Model):
    comment = models.CharField(max_length = 250)
    posted_by = models.ForeignKey(Profile, on_delete=models.CASCADE, null = True)
    commented_project = models.ForeignKey(Project, on_delete=models.CASCADE, null = True)

    def save_comments(self):
        self.save()

    def delete_comments(self):
        self.delete()
    
    def update_comment(self):
        self.update()

def __str__(self):
        return self.posted_by


class Rate(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10,'10'),
    )
    project=models.ForeignKey(Project,on_delete=models.CASCADE)
    rater=models.ForeignKey(User,on_delete=models.CASCADE)
    design_rating = models.IntegerField(choices=RATING_CHOICES,null=True)
    usability_rating=models.IntegerField(choices=RATING_CHOICES,null=True)
    content_rating=models.IntegerField(choices=RATING_CHOICES,null=True)

awwardapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile,Project, Comments, Rate

class NewProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'date', 'firstname', 'lastname']
        

class NewProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['pub_date','user','profile']


class commentForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = ['posted_by','profile','commented_project']


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        exclude=['rater','project']

awwardapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Project,Profile,Comments
from django.http  import HttpResponse,Http404
from django.contrib.auth.decorators import login_required
from .forms import NewProfileForm,NewProjectForm,commentForm, RateForm
from rest_framework.views import APIView
from django.http import JsonResponse
from rest_framework.response import Response
from .serialiser import ProfileSerializer,ProjectSerializer

# Create your views here.

def welcome(request):
    all_projects = Project.get_all_projects()
    awwardapp_users = Profile.get_all_awwardproj_users()
    current_user = request.user
    rate_form = RateForm()
    # myprof = Profile.objects.filter(id = current_user.id).first()
    # mycomm = Comments.objects.filter(id = current_user.id).first()
    return render(request, 'welcome.html', {"all_projects":all_projects, "awwardapp_users":awwardapp_users, 'rate_form':rate_form})


@login_required(login_url='/accounts/login/')
def my_profile(request):

    current_user = request.user
    profi_images = Project.objects.filter(user = current_user)
    my_profile = Profile.objects.filter(user = current_user).first()
    return render(request, 'profile.html', {"profi_images":profi_images, "my_profile":my_profile})


@login_required(login_url='/accounts/login/')
def add_profile(request):
    current_user = request.user
    profile = Profile.objects.filter(id = current_user.id)
    if request.method == 'POST':
        form = NewProfileForm(request.POST, request.FILES)
        if form.is_valid():
            caption = form.save(commit=False)
            caption.user = current_user
            caption.save()
            return redirect('myprofile')

    else:
        form = NewProfileForm()
    return render(request, 'edit_profile.html', {"form": form})


def search_users(request):
  if 'username' in request.GET and request.GET["username"]:
      search_term = request.GET.get("username")
      searched_users = Profile.search_by_profile(search_term)
      message = f"{search_term}"
      return render(request, "search.html",{"message":message,"users": searched_users})
  else:
      message = "You haven't searched for any term"
      return render(request, 'search.html',{"message":message})


@login_required(login_url='/accounts/login/')
def upload_image(request):

    current_user = request.user
    if request.method == 'POST':
        form = NewProjectForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = current_user
            image.save()
        return redirect('welcome')

    else:
        form = NewProjectForm()
    return render(request, 'upload.html', {"form": form})


@login_required(login_url='/accounts/login/')
def add_comment(request, project_id):
    current_user = request.user
    project_item = Project.objects.filter(id = project_id).first()
    profiles = Profile.objects.filter( user = current_user.id).first()
    if request.method == 'POST':
        form = commentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.posted_by = profiles
            comment.commented_project = project_item
            comment.save()
            return redirect('welcome')

    else:
        form = commentForm()
    return render(request, 'comment_form.html', {"form": form, "project_id": project_id})


def rating(request,rate_id):

    current_user = request.user
    project = get_object_or_404(Project,pk=rate_id)
    if request.method == 'POST':
        rate_form = RateForm(request.POST, request.FILES)
        if rate_form.is_valid():
            rate = rate_form.save(commit=False)
            rate.project = project
            rate.rater = current_user
            rate.save()
        return redirect('welcome')

    return render(request, 'welcome.html')



class ProfileList(APIView):
    def get(self, request, format=None):
        all_users = Profile.objects.all()
        serializers = ProfileSerializer(all_users, many=True)
        return Response(serializers.data)

class ProjectList(APIView):
    def get(self, request, format=None):
        all_projects = Project.objects.all()
        serializers = ProjectSerializer(all_projects, many=True)
        return Response(serializers.data)

awwardapp/templates/base.html
{% load bootstrap4 %}
{% load static%}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  {% if title %}
  <title>Awwards - {{title}}</title>
  {% else %}
    <title> Awwards </title>
  {% endif %}

  {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% endblock %}

</head>
<body>
    {% include "navbar.html" %}

    {% block content %} 
    {%endblock%}

    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     {% bootstrap_javascript %}
    {% endblock %}
</body>
</html>
</html>

awwardapp/templates/comment_form.html
{% load bootstrap4 %} 
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Comment</title>
  {{form.media}}

  {% block styles %} 
  {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}"> 
  {% endblock %}

</head>

<body>
<div class="container" style="margin-top:5%">

  <form  action="{%url 'comment' project_id%}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-success btn-lg" value="Post">
  </form>

   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %} {% endblock %}
</div>
</body>

</html>

awwardapp/templates/edit_profile.html
{% load bootstrap4 %} 
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Profile</title>
  {{form.media}}

  {% block styles %} 
  {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}"> 
  {% endblock %}

</head>

<body>
<div class="container" style="margin-top:5%">

  <form  action="{%url 'edit' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-success btn-lg" value="Post">
  </form>

   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %} {% endblock %}
</div>
</body>

</html>

awwardapp/templates/navbar.html
{% load bootstrap4 %}

{% block content %}

<body>
  <nav class="navbar navbar-expand-lg navbar-white bg-white static-top" style="background-color: white; margin-bottom: 8%; border-bottom: 1px solid rgba(44, 41, 41, 0.089);">
    <div class="container">

      <div class="home">
        <a class="navbar-brand" href="{%url 'welcome'%}">
          <!-- <img src="../static/phootos/instagram.png" width="50" height="50" style="border-right: 1px solid black;"> -->
          <span style="font-family: 'Satisfy', cursive; color: black; margin-left: 5%; font-size: 140%">
            Awwards
          </span>

        </a>
      </div>

      <form action="{% url 'searchs'%}" class="search text-center" style="margin-top: 2%; margin-left:5%;">
        <input type="text" class="input-sm form-control" name="username" placeholder="Search">
      </form>

      <div class="account">

        <ul class="nav justify-content-end">


          <li class="nav-item">
            <a class="nav-link" href="{%url 'upload'%}" style="color: rgb(10, 10, 10); ">Submit your site</a>
            </li>

          <li class="nav-item">
            <a class="nav-link" href="{%url 'myprofile'%}" style="color: grey;"><img src="https://files.slack.com/files-pri/T077KKCG6-FPC2K7KPD/insta12.png"
                width="30px;"></a>
          </li>

      </div>

    </div>
    </div>
  </nav>
</body>
{% endblock %}
<!-- <img src="https://files.slack.com/files-pri/T077KKCG6-FPP2R03QC/insta9.png"
                width="50px;"> -->

awwardapp/templates/profile.html
{%extends 'base.html'%}

{% block content %}
{{block.super}}
<style>
    .avatar {
        vertical-align: middle;
        width: 150px;
        height: 150px;
        border-radius: 50%;
    }

    .theprofile {
        float: left;
        width: calc(33.333% - 1rem);
        display: flex;
        justify-content: center;
        align-items: center;
        margin-right: 3rem;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="profile" style="margin-top: -7%; ">
                <img src="{{my_profile.profile_photo.url}}" class="img-responsive avatar" >
            </div>
        </div>
        <div class="col-md-3">
            <div class="imagecaption">
                <h5>{{my_profile.user}}</h5>
                <h5>{% autoescape on %}
                    {{my_profile.bio| safe}}
                    {% endautoescape %}</h5>
            </div>
        </div>
        <div class="col-md-3">
            {% if user.is_authenticated %}
            <div class="dropdown" style="margin-top: 4%">
                <a style=" color: black; " data-toggle="dropdown"> <button>Edit Profile</button> <img src="https://cdn1.iconfinder.com/data/icons/instagram-ui-colored/48/JD-01-512.png"
                        width="60px;"></a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{%url 'edit'%}" style="color: black">Add profile</a>
                    <a class="dropdown-item" href="{%url 'upload'%}" style="color: black; ">upload</a>
                    <a class="dropdown-item" href="/accounts/password/change" style="color: black">Change Password</a>
                    <a class="dropdown-item" href="/logout" style="color: black">Logout</a>
                </div>
            </div>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/accounts/login" style="color: black;">Login</a>
            </li>
            </ul>
            {% endif %}
        </div>
    </div>
    <hr>

    <div class="row">
        {% for user in profi_images %}
        <div class="col-md-4" style="width:50%;">
            <img src="{{user.image.url}}" height="300" height="200" class="img-responsive" alt="Image" style="width:100%;" ><br><br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

awwardapp/templates/rate.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}
{{block.super}}
<div class="container-fluid" id="form">
    <div class="col-md-12">
        <form id="questions" >
            <div class="row">
                <div class="col-md-6">
                    Design.
                </div>

                <div class="col-md-6">
                    <input type="radio" name="rate1" id="terrible" checked="checked" value="terrible">Terrible
                    <input type="radio" name="rate1" id="poor" value="poor">Poor
                    <input type="radio" name="rate1" id="average" value="average">Average
                    <input type="radio" name="rate1" id="very good" value="very good">Very Good
                    <input type="radio" name="rate1" id="excellent" value="excellent">Excellent

                </div>
            </div>


            <br>
            <div class="row">
                </br>
                <div class="col-md-6">
                    Usability.
                </div>

                <div class="col-md-6">
                    <input type="radio" name="rate2" id="terrible" checked="checked" value="terrible">Terrible
                    <input type="radio" name="rate2" id="poor" value="poor">Poor
                    <input type="radio" name="rate2" id="average" value="average">Average
                    <input type="radio" name="rate2" id="very good" value="very good">Very Good
                    <input type="radio" name="rate2" id="excellent" value="excellent">Excellent

                </div>
            </div>

            <br>
            <div class="row">
                </br>
                <div class="col-md-6">
                    creativity.
                </div>

                <div class="col-md-6">
                    <input type="radio" name="rate3" id="terrible" checked="checked" value="terrible">Terrible
                    <input type="radio" name="rate3" id="poor" value="poor">Poor
                    <input type="radio" name="rate3" id="average" value="average">Average
                    <input type="radio" name="rate3" id="very good" value="very good">Very Good
                    <input type="radio" name="rate3" id="excellent" value="excellent">Excellent

                </div>
            </div>

            <br>
            <button class="btn btn-outline-success" type="submit" id="submit" name="reset_form" value="Reset Form" onclick="this.form.reset();">SUBMIT</button>
        </form>
    </div>
</div>
<div id="divhidden" style="display: none;">
    <div class="col-md-8">
        <form action="{% url 'rate'  project.id %}" method="POST" enctype="multipart/form-data" id="ratingform">
            {% csrf_token %}
            {% bootstrap_form rateform %}
            <input type="submit" class="btn btn-outline-success" value="Upload">
        </form>
    </div>
</div>
{% endblock %}

awwardapp/templates/search.html
{%extends 'base.html'%} 
{% block content %}
<div class="container">

  <div class="row">
    {% if users%}
      <h2>Found {{ users|length }} of searched term {{message}}</h2>
    {% else %}
      <h2> Found 0 users for the search term {{message}}</h2>
    {% endif %}

  </div>

  <div class="row">

  {% if users %}
    {% for user in users %}
      <div class="col-sm-6 col-md-3">
        <h2 style="color:rgb(41, 39, 39)"><strong>user's profile</strong>{{user.user.username}}</h2>
      </div>
    {% endfor %}
  {% endif %}
  </div>
</div>
{% endblock %}

awwardapp/templates/upload.html
{% load bootstrap4 %} 
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Upload</title>
  {{form.media}}

  {% block styles %} 
  {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}"> 
  {% endblock %}

</head>

<body>
<div class="container" style="margin-top:5%">

  <form  action="{%url 'upload' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-success btn-lg" value="Post">
  </form>

   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %} {% endblock %}

</div>

</body>

</html>

awwardapp/templates/welcome.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% block content %}
{{block.super}}

<style>
    * {
        box-sizing: border-box;
    }


    .zoom:hover {
        -ms-transform: scale(1.0);
        /* IE 9 */
        -webkit-transform: scale(1.0);
        /* Safari 3-8 */
        transform: scale(1.5);
    }

    .text {
        color: rgb(247, 242, 246);
        font-size: 20px;
        position: absolute;
        top: 50%;
        left: 50%;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        text-align: center;
    }

    .card:hover .overlay {
        opacity: 1;
    }

    .overlay {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        height: 100%;
        width: 100%;
        opacity: 0;
        transition: .5s ease;
        background-color: rgba(58, 57, 58, 0.493);
    }
</style>

<div style="background-image:url('https://st2.depositphotos.com/2285095/8933/i/950/depositphotos_89339314-stock-photo-coffee-cup-spiral-notebook-computer.jpg'); margin-top: -10%;">
    <br>
    <h5 style="color:#f10707">Site of the day {{pub_date|date:"l d-F Y"}}</h5>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>

<div class="container">
    <div class="row">
        {% for project in all_projects %}
        <!-- <h5 style="color:#f10707">Site of the day {{project.pub_date|date:"l d-F Y"}}</h5> -->
        <div class="col-md-4">
            <div class="card" style="width: 100%;   margin-top: 20%;">

                <img src="{{project.image.url}}" height="300" class="img-responsive zoom" alt="Image" style="border-bottom: 1px solid rgba(44, 41, 41, 0.089);">
                <div class="overlay">
                    <div class="text"> <a class="img-thumbnail" href="{{project.project_image}}" data-image-id="{{project.id}}"
                            data-toggle="modal" data-target="#{{project.id}}">
                            rate
                        </a></div>
                </div>
                <p><a href="{{project.project_url}}">{{project.project_name}}</a></p>
                <p> Posted by: {{ project.user }}</p>
                <p> {{project.pub_date|timesince}}</p>

                <p>average rating: {{project.average_rating}}</p>
                <hr>
                <div class="col-md-2">
                    <a href="{%url 'comment' project.id%}" class="btn btn-default"><img src="https://cdn4.iconfinder.com/data/icons/vectory-basic/40/comment_2-512.png"
                            style="width:30px;"></a>
                </div>
                {% for comments in project.comments_set.all %}
                <h6>{{ project.user }}: {{comments.comment}} </h6>
                {% endfor %}

            </div>
            <br><br>
        </div>
        <br><br>
    </div>



    <div class="modal fade" id="{{project.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    Rate

                </div>
                <div class="modal-body">

                    <form action="{%url 'rating' project.id %}" method="post" enctype="multipart/form-data">
                        {%csrf_token%}

                        {% bootstrap_form rate_form %}
                        <input type="submit" class="btn btn-success btn-lg" value="Post">
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
    </div>


    {% endfor %}

</div>
</div>
{% endblock %}